
name: Test

on:
  push:
    branches:
      - '**' #main
    tags:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boost: [1.80.0, 1.71.0, 1.68.0]
        geant4: [11.0.3, 10.7.4, 10.2.3]
    env:
      INSTALL_PREFIX: ${{github.workspace}}/deps
    steps:
      -
        name: checkout source
        uses: actions/checkout@v3
      -
        name: cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{env.INSTALL_PREFIX}}
          key: boost-${{matrix.boost}}-geant4-${{matrix.geant4}}
      -
        name: install boost
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: |
          mkdir dep-src
          boost_version=${{matrix.boost}}
          wget -q -O - https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz |\
            tar -xz --strip-components=1 --directory dep-src
          cd dep-src
          ./bootstrap.sh --with-libraries=iostreams,math
          ./b2 install --prefix=${INSTALL_PREFIX}
          cd ..
          rm -rf dep-src
      -
        name: install geant4
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: |
          mkdir dep-src
          wget -q -O - https://github.com/geant4/geant4/archive/refs/tags/v${{matrix.geant4}}.tar.gz |\
            tar -xz --strip-components=1 --directory dep-src
          cmake \
            -DGEANT4_INSTALL_EXAMPLES=OFF \
            -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
            -B dep-src/build \
            -S dep-src
          cmake --build dep-src/build --target install
          rm -rf dep-src 
      -
        name: test compile
        run: |
          source ${INSTALL_PREFIX}/bin/geant4.sh
          export CMAKE_PREFIX_PATH=${INSTALL_PREFIX}
          cmake -B build -S . 
          cmake --build build

